### ISSUE TITLE
Awesome work!

### ISSUE THREAD

**Issue by nodkz** [jbdemonte/mongoose-elasticsearch-xp#10]
I like what you've done. Awesome work!

Try to integrate it with my internal project and write new plugin for [graphql-compose](https://github.com/nodkz/graphql-compose): `graphql-compose-mongoose-elasticsearch-xp`.

Did you plan to drastically change API in the near future? Or it's quite stable for now?

**Comment by jbdemonte** [comment]
Nop, I just updated to support Elasticsearch 5, no plan for any change right now :)

**Comment by nodkz** [comment]
Will you accept PRs for:
1. adding `yarn.lock`
2. changing `jshint` on `eslint`
3. adding `prettier` (which change a little bit your code style)
4. migration from `mocha` to `jest` for better test runs

**Comment by nodkz** [comment]
Also will be nice to setup semantic releasing with automatic package publishing https://egghead.io/lessons/javascript-how-to-write-a-javascript-library-writing-conventional-commits-with-commitizen

**Comment by jbdemonte** [comment]
I'm open to discover practice I've not yet
