### ISSUE TITLE
Using let, const and arrow functions in code.

### ISSUE THREAD

**Issue by nodkz** [jbdemonte/mongoose-elasticsearch-xp#14]
Due dropping support for node below v4 and due [kangax](https://kangax.github.io/compat-table/es6/) compatibility I recommend cleanup tests and start using `let`, `const` and `arrow functions`.

Node4 does not support some features from ES6 with let and const, but they will not bring any downsides and errors. Can be used safely for the current codebase.

Tests with arrow functions become much clearer.

With pleasure refactor code and setup additional eslint rules for checking this.

**Comment by jbdemonte** [comment]
that's right that for now, I've still my ES5 habits

**Comment by nodkz** [comment]
@jbdemonte can I convert all functions in tests as addition to my current PR for your weekend review?

**Comment by jbdemonte** [comment]
yes, thanks

**Comment by jbdemonte** [comment]
a point, keep the node 4.x support, there are still a lot of people / companies which use it

**Comment by nodkz** [comment]
Don't worry, node 4 will work. 
For now, I just migrate tests and after PR review we decide when and how to change/upgrade basic code.
