### ISSUE TITLE
Move `elasticsearch` and `mongoose` to peerDependencies

### ISSUE THREAD

**Issue by nodkz** [jbdemonte/mongoose-elasticsearch-xp#15]
Better to move `elasticsearch` and `mongoose` to peerDependencies. Users should install it explicitly in their app. 

Also it solves problem of different versions `elasticsearch` and `mongoose` in your lib and version which have users in their `package.json` already.

A long time ago I did the same things with my `graphql-compose` and it works perfectly.
Ready to make such PR, after you accept my current PRs.

**Comment by jbdemonte** [comment]
Right now, I'll have no time to have a deep look on your PR, I plan to check everything this week-end.
In the interval, there is something which "hurted" me ;) even if I understand the "why", I can resolve myself to let trailing comma in JS :) Is it a requirement of prettier or any modern "good practice"?
I followed till now the Douglas Crockford syntax

**Comment by nodkz** [comment]
Yep, `prettier` do this.
It also hurt me first time, but quickly got used to it. The more recently it becomes as "good practice" (arguments described in eslint rule here http://eslint.org/docs/rules/comma-dangle). Overall `eslint` contains a lot of useful rules derived by community and always updates. I quite fast improve my skills with it when migrated from ruby to js and from es5 to es6. Also eslint provide `Fix` button for auto-replace eg. `"text"` to `'text'`, or `{a:1}` to `{ a:1 }`. Any rule can be disabled as you wish.


About Prettier. I'd full in love with prettier especialy in tests:
Eg. console.log return me something like this:
```
{ "custom_french_analyzer": {  "tokenizer": "letter",  "filter": ["asciifolding", "lowercase", "french_stem", "elision", "stop"]  },  "tag_analyzer": {  "tokenizer": "keyword", "filter": ["asciifolding", "lowercase"]  }  }
```
Put this to `.eql` in test, press `ctrl+alt/option+f` and as result obtain such well formated code in just millisecond:
```js
        expect(analysis.analyzer).to.eql({
          custom_french_analyzer: {
            tokenizer: 'letter',
            filter: [
              'asciifolding',
              'lowercase',
              'french_stem',
              'elision',
              'stop',
            ],
          },
          tag_analyzer: {
            tokenizer: 'keyword',
            filter: ['asciifolding', 'lowercase'],
          },
        });
``` 
I'm using `Atom` + `Nuclide` (awesome plugin from facebook for atom), and for using prettier (via hot key `ctrl+alt/option+f`) I install `prettier-atom` from James Long to use it in projects where prettier does not installed as eslint rule. Also recommend `js-hyperclick` atom plugin for obtaining `ctrl+click` for skipping to func/vars declarations.
