### ISSUE TITLE
Does this plugin support parent / child relationships

### ISSUE THREAD

**Issue by whnunlife** [jbdemonte/mongoose-elasticsearch-xp#21]
Curious if this plugin supports the parent / child relationships?

**Comment by jbdemonte** [comment]
what do you mean?

**Comment by whnunlife** [comment]
So, when saving a doc in elastic search, you can specify if the doc has a parent:

https://www.elastic.co/guide/en/elasticsearch/guide/current/indexing-parent-child.html#indexing-parent-child

**Comment by jbdemonte** [comment]
There is an equivalent in mongoose?

**Comment by whnunlife** [comment]
http://mongoosejs.com/docs/populate.html

**Comment by jbdemonte** [comment]
https://github.com/jbdemonte/mongoose-elasticsearch-xp#indexing-populated-models

**Comment by whnunlife** [comment]
Thanks, i'll take a closer look.
