### ISSUE TITLE
TypeError: doc.esIndex(...).then(...).then(...).catch is not a function

### ISSUE THREAD

**Issue by sidharthchugh** [jbdemonte/mongoose-elasticsearch-xp#25]
As i am getting bellow issue with mongoosastic 

https://github.com/Automattic/mongoose/issues/4998

because i have 9,000 documents so i used your library , it works for existing document but my whole app breaks when i perform bellow query.

 Profile.findOneAndUpdate({elasticId: req.headers.userid},
     req.body,
     {new: true}, callback);

Note: with mongoosastic this query is working.

Mongoose version : 4.2.2
ES version: 5.4.0

**Comment by jbdemonte** [comment]
what is the content of `req.body` ?
