### ISSUE TITLE
Migrating from Mongoosastic

### ISSUE THREAD

**Issue by muhammadfaizan** [jbdemonte/mongoose-elasticsearch-xp#30]
Hey,
Im glad to see this module coming up in just the right time, I have started a new project and was wondering can I replace old mongoosastic with this module and not face any error !?

Would you recommend doing that? Since its a fork of mongoosastic.

**Comment by jbdemonte** [comment]
It's not a fork of mongoosastic :)
It coded from near scratch, I only kept the ReadMe and the Syntax / Philosophy (which is not node ;) )

**Comment by muhammadfaizan** [comment]
I found a couple of things that could be of improvement, would be giving a few PR soon

**Comment by jbdemonte** [comment]
Great, thanks :)
