### ISSUE TITLE
esSynchronize not working

### ISSUE THREAD

**Issue by t4nz** [jbdemonte/mongoose-elasticsearch-xp#41]
Tested with mongoose "^5.0.4".

I have an issue running the esSynchronize method:

> TypeError: Cannot read property 'on' of undefined
>     at utils.run (/../node_modules/mongoose-elasticsearch-xp/lib/index.js:378:12)

The issue is caused by the variable "stream" (line 331), which assumes the undefined value due to the .stream query method.

As reported in the mongoose [changelog](https://github.com/Automattic/mongoose/blob/1ead0e616ab028a994ab47a23643749659243e07/History.md#500-rc0--2017-12-28), the **.stream()** method should be replaced with the **.cursor()** method. I tried to replace it and it works properly.

```if (conditions instanceof mongoose.Query) {
      stream = conditions
        .lean()
        .batchSize(batch)
-       .stream();
+       .cursor();
    } else {
      stream = model
        .find(conditions || {}, projection, options)
        .lean()
        .batchSize(batch)
-      .stream();
+      .cursor();
    }

**Comment by nodkz** [comment]
Thanks for reporting. 
New package version will be automatically published after CI tests.
