### ISSUE TITLE
Model.remove fails in getting documents unindexed

### ISSUE THREAD

**Issue by jeremythille** [jbdemonte/mongoose-elasticsearch-xp#5]
Using Mongoose's method `Model.remove()` effectively removes the documents from Mongo, but they remain indexed in Elastic's base.

```
Ad.remove({
  $where: "this.site.length > 0"
}).exec(function(err, docs) {
     if(err) throw err;
     console.log(docs); // undefined!
});
```

Many documents are removed from Mongo, but they remain in Elastic.

My guess is that Mexp needs the returned documents in order to update them in ES, but the problem is that the `remove()` method [does not return these documents](http://mongoosejs.com/docs/api.html#query_Query-remove). Its signature is only `err`.

**Workaround**
We can make a 2-step delete, with (1) a `find()` query and (2) delete the returned documents one by one. `findOneAndRemove()` returns the deleted document, so it can be unindexed.

**Comment by jbdemonte** [comment]
Yes, mexp only handle document's handlers, not model ones
