### ISSUE TITLE
Is this repo still maintained?

### ISSUE THREAD

**Issue by ruizmarc** [jbdemonte/mongoose-elasticsearch-xp#65]
Hi!

mongoose-elasticsearch-xp is such a great library and very useful for us. However, since a time ago, it seems this library is not getting so much attention, for example, it has not received the update of the elastic client that the library has not adopted yet.

I don't mind to help maintaing the repo @jbdemonte, but if you don't plan to keep maintaing it, maybe, it would be great to mark the repo as Unmaintaned, so any other can do a fork and keep this project alive as an alternative to this one. 

Best regards

**Comment by jbdemonte** [comment]
Hi @ruizmarc 

It's just a delay... I had some personal problem to handle, so, I've been pretty AFK / AF open source projects for a while

@nodkz has done a really cool & pro work by updating a large part of mexp. I didn't exchange with him in this period. but I will.

I think being back in a few weeks, no idea for @nodkz (plz answer to this thread)

![image](https://user-images.githubusercontent.com/787639/76029541-f6191b00-5f34-11ea-9109-7c4e7855c55a.png)

**Comment by ruizmarc** [comment]
Hi @jbdemonte 

It's very nice to hear that you still plan to keep pushing forward this library. I hope you can manage your problems and get you back soon :)

**Comment by nodkz** [comment]
I'm in stealth mode – can accept PRs but have no time to do something myself.
Too much work in other repos.
