### ISSUE TITLE
Support for populate and index ?

### ISSUE THREAD

**Issue by abhaypai2611** [jbdemonte/mongoose-elasticsearch-xp#7]
Hello,

Does MExp support populate and index feature from Mongoosastic ? Basically even I was facing issues with mongoosastic and I was going to start a plugin for Mongo + ES by myself. I just came across your plugin and it looks promising !

In mongoosastic when I try to do projection with "fields" / "_source", I get  "query_parsing_exception". I am trying to make a workaround for the same. Let's hope for the best.

Cheers !

**Comment by jbdemonte** [comment]
You can now use es_type as an object to support it (have a look on https://github.com/jbdemonte/mongoose-elasticsearch-xp/blob/master/test/model-mapping.js#L652)
Notice you'll have to populate your data, the plugin won't

**Comment by prakharsingh** [comment]
@jbdemonte `This plugin will never populate models by its own, you have to populate the models.` What do you mean by this? I am trying to synchronize existing data and populate doesn't work.

```
const participantSchema = Mongoose.Schema({
  role: String,
  user: {
    type: Mongoose.Schema.Types.ObjectId,
    ref: 'user'
  }
}, { _id : false });

const conferenceSchema = new Schema({
  participants: {
    type: [ participantSchema ],
    es_indexed: true,
    es_type: {
      role: {
        es_type: 'string'
      },
      user: {
        es_type: {
          firstName: {
            es_type: 'string'
          },
          lastName: {
            es_type: 'string'
          },
          email: {
            es_type: 'string'
          }
        }
      }
    }
  }
})
```

Here is the mapping:

```
mappings": {
      "conference": {
        "properties": {
          "participants": {
            "properties": {
              "role": {
                "type": "text",
                "fields": {
                  "keyword": {
                    "type": "keyword",
                    "ignore_above": 256
                  }
                }
              }
            }
          }
        }
      }
    }

```
And the source:

```
"_source": {
    "participants": [
      {
        "role": "user"
      },
      {
        "role": "admin"
      }
    ]
}
```

Thanks
